#include <iostream>
#include <TFile.h>
#include <TTree.h>
#include <TH1D.h>
#include <TChain.h>
#include <TStyle.h>
#include "../commonUtility.h"
#include "../cutsAndBin.h"

using namespace std;
void compare_Eff()
{
    gStyle->SetOptStat(0);
    gStyle->SetPadTickY(1);

    float pos_x = 0.15;
	float pos_y = 0.83;
	float pos_y_diff = 0.051;
	int text_color = 1;
	float text_size = 15;

    TFile *f1 = new TFile("./roots/mc_eff_vs_pt_cent_0_to_180_rap_prompt_pbpb_JPsi_PtWnomi_tnp1_260123.root"); // w\o ctau cut
    TFile *f2 = new TFile("./roots/mc_eff_vs_pt_cent_0_to_180_rap_prompt_pbpb_JPsi_PtWnomi_tnp1_ctauCut_260123.root"); // w/ ctau cut

    TFile *f1_pp_jpsi = new TFile("./roots/mc_eff_vs_pt_rap_prompt_pp_Jpsi_PtWnomi_tnp1_ctauCut_251104.root"); // w\o ctau cut
    TFile *f2_pp_jpsi = new TFile("./roots/mc_eff_vs_pt_rap_prompt_pp_Jpsi_PtWnomi_tnp1_ctauCut_260126.root"); // w/ ctau cut

    TFile *f1_pbpb_psi2s = new TFile("./roots/mc_eff_vs_pt_cent_0_to_180_rap_prompt_pbpb_psi2s_PtW1_tnp1_ctauCut_251103.root"); // w\o ctau cut
    TFile *f2_pbpb_psi2s = new TFile("./roots/mc_eff_vs_pt_cent_0_to_180_rap_prompt_pbpb_psi2s_PtW1_tnp1_ctauCut_260126.root"); // w/ ctau cut

    TFile *f1_pp_psi2s = new TFile("./roots/mc_eff_vs_pt_rap_prompt_pp_psi2s_PtW1_tnp1_20230728.root"); // w\o ctau cut
    TFile *f2_pp_psi2s = new TFile("./roots/mc_eff_vs_pt_rap_prompt_pp_psi2s_PtW1_tnp1_ctauCut_260126.root"); // w/ ctau cut

    TH1D *h_eff1 = (TH1D*)f1->Get("mc_eff_vs_pt_TnP1_PtW1_cent_0_to_180_absy1p6_2p4");
    TH1D *h_eff2 = (TH1D*)f2->Get("mc_eff_vs_pt_TnP1_PtW1_cent_0_to_180_absy1p6_2p4");

    TH1D *h_eff3 = (TH1D*)f1->Get("mc_eff_vs_pt_TnP1_PtW1_cent_0_to_180_absy0_1p6");
    TH1D *h_eff4 = (TH1D*)f2->Get("mc_eff_vs_pt_TnP1_PtW1_cent_0_to_180_absy0_1p6");

    TH1D *h_eff_pp_fwd_1 = (TH1D*)f1_pp_jpsi->Get("mc_eff_vs_pt_TnP1_PtW1_absy1p6_2p4");
    TH1D *h_eff_pp_fwd_2 = (TH1D*)f2_pp_jpsi->Get("mc_eff_vs_pt_TnP1_PtW1_absy1p6_2p4");
    TH1D *h_eff_pp_mid_1 = (TH1D*)f1_pp_jpsi->Get("mc_eff_vs_pt_TnP1_PtW1_absy0_1p6");
    TH1D *h_eff_pp_mid_2 = (TH1D*)f2_pp_jpsi->Get("mc_eff_vs_pt_TnP1_PtW1_absy0_1p6");

    TH1D *h_eff_pbpb_psi2s_fwd_1 = (TH1D*)f1_pbpb_psi2s->Get("mc_eff_vs_pt_TnP1_PtW1_cent_0_to_180_absy1p6_2p4");
    TH1D *h_eff_pbpb_psi2s_fwd_2 = (TH1D*)f2_pbpb_psi2s->Get("mc_eff_vs_pt_TnP1_PtW1_cent_0_to_180_absy1p6_2p4");
    TH1D *h_eff_pbpb_psi2s_mid_1 = (TH1D*)f1_pbpb_psi2s->Get("mc_eff_vs_pt_TnP1_PtW1_cent_0_to_180_absy0_1p6");
    TH1D *h_eff_pbpb_psi2s_mid_2 = (TH1D*)f2_pbpb_psi2s->Get("mc_eff_vs_pt_TnP1_PtW1_cent_0_to_180_absy0_1p6");

    TH1D *h_eff_cent_fwd_1 = (TH1D*)f1->Get("mc_eff_vs_cent_TnP1_PtW1_pt_3_to_40_absy1p6_2p4");
    TH1D *h_eff_cent_fwd_2 = (TH1D*)f2->Get("mc_eff_vs_cent_TnP1_PtW1_pt_3_to_40_absy1p6_2p4");
    TH1D *h_eff_cent_mid_1 = (TH1D*)f1->Get("mc_eff_vs_cent_TnP1_PtW1_pt_6p5_to_40_absy0_1p6");
    TH1D *h_eff_cent_mid_2 = (TH1D*)f2->Get("mc_eff_vs_cent_TnP1_PtW1_pt_6p5_to_40_absy0_1p6");

    TH1D *h_eff_cent_pbpb_psi2s_fwd_1 = (TH1D*)f1_pbpb_psi2s->Get("mc_eff_vs_cent_TnP1_PtW1_pt_3_to_40_absy1p6_2p4");
    TH1D *h_eff_cent_pbpb_psi2s_fwd_2 = (TH1D*)f2_pbpb_psi2s->Get("mc_eff_vs_cent_TnP1_PtW1_pt_3_to_40_absy1p6_2p4");
    TH1D *h_eff_cent_pbpb_psi2s_mid_1 = (TH1D*)f1_pbpb_psi2s->Get("mc_eff_vs_cent_TnP1_PtW1_pt_6p5_to_40_absy0_1p6");
    TH1D *h_eff_cent_pbpb_psi2s_mid_2 = (TH1D*)f2_pbpb_psi2s->Get("mc_eff_vs_cent_TnP1_PtW1_pt_6p5_to_40_absy0_1p6");

    TH1D *h_eff_pp_psi2s_fwd_1 = (TH1D*)f1_pp_psi2s->Get("mc_eff_vs_pt_TnP1_PtW1_absy1p6_2p4");
    TH1D *h_eff_pp_psi2s_fwd_2 = (TH1D*)f2_pp_psi2s->Get("mc_eff_vs_pt_TnP1_PtW1_absy1p6_2p4");
    TH1D *h_eff_pp_psi2s_mid_1 = (TH1D*)f1_pp_psi2s->Get("mc_eff_vs_pt_TnP1_PtW1_absy0_1p6");
    TH1D *h_eff_pp_psi2s_mid_2 = (TH1D*)f2_pp_psi2s->Get("mc_eff_vs_pt_TnP1_PtW1_absy0_1p6");

    TCanvas* c_pT_fwd = new TCanvas("c_pT_fwd","",550,520);
    c_pT_fwd->cd();
    TPad *pad_A_1 = new TPad("pad_A_1","",0,0.16,0.98,1);
    pad_A_1->SetBottomMargin(0.056);
    pad_A_1->SetTicks(1,1);
    pad_A_1->Draw();
    pad_A_1->cd();
    h_eff1->SetLineColor(kBlue+2);
    h_eff1->SetMarkerColor(kBlue+2);
    h_eff1->SetMarkerStyle(20);
    h_eff2->SetLineColor(kRed+2);
    h_eff2->SetMarkerColor(kRed+2);
    h_eff2->SetMarkerStyle(21);
    h_eff1->SetTitle("");
    h_eff1->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_eff1->GetYaxis()->SetTitle("Efficiency");
    h_eff1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff1->GetXaxis()->SetRangeUser(3.5, 40);
    h_eff2->GetXaxis()->SetRangeUser(3.5, 40);
    h_eff1->Draw("PE");
    h_eff2->Draw("PE same"); 

    auto legend = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend->AddEntry(h_eff1, "Without ctau cut", "lep");
    legend->AddEntry(h_eff2, "With ctau cut", "lep");
    legend->SetBorderSize(0);
    legend->SetFillColor(0);
    legend->Draw("E");
    
    drawText("1.6 < |y| < 2.4", pos_x, pos_y, text_color, text_size);
    drawText("3.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("Cent. 0-90%", pos_x, pos_y - pos_y_diff*2, text_color, text_size);
    
    TPad *pad_A_2 = new TPad("pad_A_2","",0,0.06,0.98,0.227);
    c_pT_fwd->cd();
    pad_A_2->Draw();
    pad_A_2->cd();
    pad_A_2->SetTopMargin(0);
    pad_A_2->SetBottomMargin(0.34);
    pad_A_2->SetFillColor(0);
    pad_A_2->SetBorderMode(0);
    pad_A_2->SetBorderSize(2);
    TH1D *h_ratio = (TH1D*)h_eff2->Clone("h_ratio");
    h_ratio->Divide(h_eff1);
    h_ratio->SetTitle("");
    h_ratio->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_ratio->GetYaxis()->SetTitle("Ratio");
    h_ratio->GetYaxis()->CenterTitle();
    h_ratio->GetXaxis()->CenterTitle();
    h_ratio->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio->GetYaxis()->SetNdivisions(505);
    h_ratio->GetYaxis()->SetTitleSize(0.17);
    h_ratio->GetYaxis()->SetTitleOffset(0.28);
    h_ratio->GetYaxis()->SetLabelSize(0.16);
    h_ratio->GetYaxis()->SetLabelOffset(0.005);
    h_ratio->GetXaxis()->SetTitleSize(0.16);
    h_ratio->GetXaxis()->SetLabelSize(0.16);
    h_ratio->GetXaxis()->SetTitleOffset(1.);
    h_ratio->GetXaxis()->SetTickLength(0.11);
    h_ratio->SetLineColor(kBlack);
    h_ratio->SetMarkerColor(kBlack);
    h_ratio->SetMarkerStyle(20);
    h_ratio->Draw("PE");   
    jumSun(3.5,0.9,40,0.9);
    c_pT_fwd->SaveAs("./figs_ctauCut/compare_Eff_pT_fwd.pdf");

    TCanvas* c_pT_mid = new TCanvas("c_pT_mid","",550,520);
    c_pT_mid->cd();
    TPad *pad_B_1 = new TPad("pad_B_1","",0,0.16,0.98,1);
    pad_B_1->SetBottomMargin(0.056);
    pad_B_1->SetTicks(1,1);
    pad_B_1->Draw();
    pad_B_1->cd();
    h_eff3->SetLineColor(kBlue+2);
    h_eff3->SetMarkerColor(kBlue+2);
    h_eff3->SetMarkerStyle(20);
    h_eff4->SetLineColor(kRed+2);
    h_eff4->SetMarkerColor(kRed+2);
    h_eff4->SetMarkerStyle(21);
    h_eff3->SetTitle("");
    h_eff3->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_eff3->GetYaxis()->SetTitle("Efficiency");
    h_eff3->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff3->GetXaxis()->SetRangeUser(6.5, 40);
    h_eff4->GetXaxis()->SetRangeUser(6.5, 40);
    h_eff3->Draw("PE");
    h_eff4->Draw("PE same"); 

    drawText("|y| < 1.6", pos_x, pos_y, text_color, text_size);
    drawText("6.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("Cent. 0-90%", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    auto legend_B = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_B->AddEntry(h_eff3, "Without ctau cut", "lep");
    legend_B->AddEntry(h_eff4, "With ctau cut", "lep");
    legend_B->SetBorderSize(0);
    legend_B->SetFillColor(0);
    legend_B->Draw("E");
    
    TPad *pad_B_2 = new TPad("pad_B_2","",0,0.06,0.98,0.227);
    c_pT_mid->cd();
    pad_B_2->Draw();
    pad_B_2->cd();
    pad_B_2->SetTopMargin(0);
    pad_B_2->SetBottomMargin(0.34);
    pad_B_2->SetFillColor(0);
    pad_B_2->SetBorderMode(0);
    pad_B_2->SetBorderSize(2);
    TH1D *h_ratio_mid = (TH1D*)h_eff4->Clone("h_ratio_mid");
    h_ratio_mid->Divide(h_eff3);
    h_ratio_mid->SetTitle("");
    h_ratio_mid->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_ratio_mid->GetYaxis()->SetTitle("Ratio");
    h_ratio_mid->GetYaxis()->CenterTitle();
    h_ratio_mid->GetXaxis()->CenterTitle();
    h_ratio_mid->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_mid->GetYaxis()->SetNdivisions(505);
    h_ratio_mid->GetYaxis()->SetTitleSize(0.17);
    h_ratio_mid->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_mid->GetYaxis()->SetLabelSize(0.16);
    h_ratio_mid->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_mid->GetXaxis()->SetTitleSize(0.16);
    h_ratio_mid->GetXaxis()->SetLabelSize(0.16);
    h_ratio_mid->GetXaxis()->SetTitleOffset(1.);
    h_ratio_mid->GetXaxis()->SetTickLength(0.11);
    h_ratio_mid->SetLineColor(kBlack);
    h_ratio_mid->SetMarkerColor(kBlack);
    h_ratio_mid->SetMarkerStyle(20);
    h_ratio_mid->Draw("PE");   
    jumSun(6.5,0.9,40,0.9);
    c_pT_mid->SaveAs("./figs_ctauCut/compare_Eff_pT_mid.pdf");

    TCanvas* c_pT_fwd_pp_jpsi = new TCanvas("c_pT_fwd_pp_jpsi","",550,520);
    c_pT_fwd_pp_jpsi->cd();
    TPad *pad_C_1 = new TPad("pad_C_1","",0,0.16,0.98,1);
    pad_C_1->SetBottomMargin(0.056);
    pad_C_1->SetTicks(1,1);
    pad_C_1->Draw();
    pad_C_1->cd();
    h_eff_pp_fwd_1->SetLineColor(kBlue+2);
    h_eff_pp_fwd_1->SetMarkerColor(kBlue+2);
    h_eff_pp_fwd_1->SetMarkerStyle(20);
    h_eff_pp_fwd_2->SetLineColor(kRed+2);
    h_eff_pp_fwd_2->SetMarkerColor(kRed+2);
    h_eff_pp_fwd_2->SetMarkerStyle(21);
    h_eff_pp_fwd_1->SetTitle("");
    h_eff_pp_fwd_1->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_eff_pp_fwd_1->GetYaxis()->SetTitle("Efficiency");
    h_eff_pp_fwd_1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff_pp_fwd_1->GetXaxis()->SetRangeUser(3.5, 40);
    h_eff_pp_fwd_2->GetXaxis()->SetRangeUser(3.5, 40);
    h_eff_pp_fwd_1->Draw("PE");
    h_eff_pp_fwd_2->Draw("PE same");

    auto legend_C = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_C->AddEntry(h_eff_pp_fwd_1, "Without ctau cut", "lep");
    legend_C->AddEntry(h_eff_pp_fwd_2, "With ctau cut", "lep");
    legend_C->SetBorderSize(0);
    legend_C->SetFillColor(0);
    legend_C->Draw("E");

    drawText("1.6 < |y| < 2.4", pos_x, pos_y, text_color, text_size);
    drawText("3.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("pp", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    TPad *pad_C_2 = new TPad("pad_C_2","",0,0.06,0.98,0.227);
    c_pT_fwd_pp_jpsi->cd();
    pad_C_2->Draw();
    pad_C_2->cd();
    pad_C_2->SetTopMargin(0);
    pad_C_2->SetBottomMargin(0.34);
    pad_C_2->SetFillColor(0);
    pad_C_2->SetBorderMode(0);
    pad_C_2->SetBorderSize(2);
    TH1D *h_ratio_pp_fwd = (TH1D*)h_eff_pp_fwd_2->Clone("h_ratio_pp_fwd");
    h_ratio_pp_fwd->Divide(h_eff_pp_fwd_1);
    h_ratio_pp_fwd->SetTitle("");
    h_ratio_pp_fwd->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_ratio_pp_fwd->GetYaxis()->SetTitle("Ratio");
    h_ratio_pp_fwd->GetYaxis()->CenterTitle();
    h_ratio_pp_fwd->GetXaxis()->CenterTitle();
    h_ratio_pp_fwd->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_pp_fwd->GetYaxis()->SetNdivisions(505);
    h_ratio_pp_fwd->GetYaxis()->SetTitleSize(0.17);
    h_ratio_pp_fwd->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_pp_fwd->GetYaxis()->SetLabelSize(0.16);
    h_ratio_pp_fwd->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_pp_fwd->GetXaxis()->SetTitleSize(0.16);
    h_ratio_pp_fwd->GetXaxis()->SetLabelSize(0.16);
    h_ratio_pp_fwd->GetXaxis()->SetTitleOffset(1.);
    h_ratio_pp_fwd->GetXaxis()->SetTickLength(0.11);
    h_ratio_pp_fwd->SetLineColor(kBlack);
    h_ratio_pp_fwd->SetMarkerColor(kBlack);
    h_ratio_pp_fwd->SetMarkerStyle(20);
    h_ratio_pp_fwd->Draw("PE");
    jumSun(3.5,0.9,40,0.9);
    c_pT_fwd_pp_jpsi->SaveAs("./figs_ctauCut/compare_Eff_pT_fwd_pp_Jpsi.pdf");

    TCanvas* c_pT_mid_pp_jpsi = new TCanvas("c_pT_mid_pp_jpsi","",550,520);
    c_pT_mid_pp_jpsi->cd();
    TPad *pad_D_1 = new TPad("pad_D_1","",0,0.16,0.98,1);
    pad_D_1->SetBottomMargin(0.056);
    pad_D_1->SetTicks(1,1);
    pad_D_1->Draw();
    pad_D_1->cd();
    h_eff_pp_mid_1->SetLineColor(kBlue+2);
    h_eff_pp_mid_1->SetMarkerColor(kBlue+2);
    h_eff_pp_mid_1->SetMarkerStyle(20);
    h_eff_pp_mid_2->SetLineColor(kRed+2);
    h_eff_pp_mid_2->SetMarkerColor(kRed+2);
    h_eff_pp_mid_2->SetMarkerStyle(21);
    h_eff_pp_mid_1->SetTitle("");
    h_eff_pp_mid_1->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_eff_pp_mid_1->GetYaxis()->SetTitle("Efficiency");
    h_eff_pp_mid_1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff_pp_mid_1->GetXaxis()->SetRangeUser(6.5, 40);
    h_eff_pp_mid_2->GetXaxis()->SetRangeUser(6.5, 40);
    h_eff_pp_mid_1->Draw("PE");
    h_eff_pp_mid_2->Draw("PE same");

    auto legend_D = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_D->AddEntry(h_eff_pp_mid_1, "Without ctau cut", "lep");
    legend_D->AddEntry(h_eff_pp_mid_2, "With ctau cut", "lep");
    legend_D->SetBorderSize(0);
    legend_D->SetFillColor(0);
    legend_D->Draw("E");

    drawText("|y| < 1.6", pos_x, pos_y, text_color, text_size);
    drawText("6.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("pp", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    TPad *pad_D_2 = new TPad("pad_D_2","",0,0.06,0.98,0.227);
    c_pT_mid_pp_jpsi->cd();
    pad_D_2->Draw();
    pad_D_2->cd();
    pad_D_2->SetTopMargin(0);
    pad_D_2->SetBottomMargin(0.34);
    pad_D_2->SetFillColor(0);
    pad_D_2->SetBorderMode(0);
    pad_D_2->SetBorderSize(2);
    TH1D *h_ratio_pp_mid = (TH1D*)h_eff_pp_mid_2->Clone("h_ratio_pp_mid");
    h_ratio_pp_mid->Divide(h_eff_pp_mid_1);
    h_ratio_pp_mid->SetTitle("");
    h_ratio_pp_mid->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_ratio_pp_mid->GetYaxis()->SetTitle("Ratio");
    h_ratio_pp_mid->GetYaxis()->CenterTitle();
    h_ratio_pp_mid->GetXaxis()->CenterTitle();
    h_ratio_pp_mid->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_pp_mid->GetYaxis()->SetNdivisions(505);
    h_ratio_pp_mid->GetYaxis()->SetTitleSize(0.17);
    h_ratio_pp_mid->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_pp_mid->GetYaxis()->SetLabelSize(0.16);
    h_ratio_pp_mid->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_pp_mid->GetXaxis()->SetTitleSize(0.16);
    h_ratio_pp_mid->GetXaxis()->SetLabelSize(0.16);
    h_ratio_pp_mid->GetXaxis()->SetTitleOffset(1.);
    h_ratio_pp_mid->GetXaxis()->SetTickLength(0.11);
    h_ratio_pp_mid->SetLineColor(kBlack);
    h_ratio_pp_mid->SetMarkerColor(kBlack);
    h_ratio_pp_mid->SetMarkerStyle(20);
    h_ratio_pp_mid->Draw("PE");
    jumSun(6.5,0.9,40,0.9);
    c_pT_mid_pp_jpsi->SaveAs("./figs_ctauCut/compare_Eff_pT_mid_pp_Jpsi.pdf");

    TCanvas* c_pT_fwd_pbpb_psi2s = new TCanvas("c_pT_fwd_pbpb_psi2s","",550,520);
    c_pT_fwd_pbpb_psi2s->cd();
    TPad *pad_E_1 = new TPad("pad_E_1","",0,0.16,0.98,1);
    pad_E_1->SetBottomMargin(0.056);
    pad_E_1->SetTicks(1,1);
    pad_E_1->Draw();
    pad_E_1->cd();
    h_eff_pbpb_psi2s_fwd_1->SetLineColor(kBlue+2);
    h_eff_pbpb_psi2s_fwd_1->SetMarkerColor(kBlue+2);
    h_eff_pbpb_psi2s_fwd_1->SetMarkerStyle(20);
    h_eff_pbpb_psi2s_fwd_2->SetLineColor(kRed+2);
    h_eff_pbpb_psi2s_fwd_2->SetMarkerColor(kRed+2);
    h_eff_pbpb_psi2s_fwd_2->SetMarkerStyle(21);
    h_eff_pbpb_psi2s_fwd_1->SetTitle("");
    h_eff_pbpb_psi2s_fwd_1->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_eff_pbpb_psi2s_fwd_1->GetYaxis()->SetTitle("Efficiency");
    h_eff_pbpb_psi2s_fwd_1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff_pbpb_psi2s_fwd_1->GetXaxis()->SetRangeUser(3.5, 40);
    h_eff_pbpb_psi2s_fwd_2->GetXaxis()->SetRangeUser(3.5, 40);
    h_eff_pbpb_psi2s_fwd_1->Draw("PE");
    h_eff_pbpb_psi2s_fwd_2->Draw("PE same");

    auto legend_E = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_E->AddEntry(h_eff_pbpb_psi2s_fwd_1, "Without ctau cut", "lep");
    legend_E->AddEntry(h_eff_pbpb_psi2s_fwd_2, "With ctau cut", "lep");
    legend_E->SetBorderSize(0);
    legend_E->SetFillColor(0);
    legend_E->Draw("E");

    drawText("1.6 < |y| < 2.4", pos_x, pos_y, text_color, text_size);
    drawText("3.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("PbPb, #psi(2S)", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    TPad *pad_E_2 = new TPad("pad_E_2","",0,0.06,0.98,0.227);
    c_pT_fwd_pbpb_psi2s->cd();
    pad_E_2->Draw();
    pad_E_2->cd();
    pad_E_2->SetTopMargin(0);
    pad_E_2->SetBottomMargin(0.34);
    pad_E_2->SetFillColor(0);
    pad_E_2->SetBorderMode(0);
    pad_E_2->SetBorderSize(2);
    TH1D *h_ratio_pbpb_psi2s_fwd = (TH1D*)h_eff_pbpb_psi2s_fwd_2->Clone("h_ratio_pbpb_psi2s_fwd");
    h_ratio_pbpb_psi2s_fwd->Divide(h_eff_pbpb_psi2s_fwd_1);
    h_ratio_pbpb_psi2s_fwd->SetTitle("");
    h_ratio_pbpb_psi2s_fwd->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_ratio_pbpb_psi2s_fwd->GetYaxis()->SetTitle("Ratio");
    h_ratio_pbpb_psi2s_fwd->GetYaxis()->CenterTitle();
    h_ratio_pbpb_psi2s_fwd->GetXaxis()->CenterTitle();
    h_ratio_pbpb_psi2s_fwd->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_pbpb_psi2s_fwd->GetYaxis()->SetNdivisions(505);
    h_ratio_pbpb_psi2s_fwd->GetYaxis()->SetTitleSize(0.17);
    h_ratio_pbpb_psi2s_fwd->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_pbpb_psi2s_fwd->GetYaxis()->SetLabelSize(0.16);
    h_ratio_pbpb_psi2s_fwd->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_pbpb_psi2s_fwd->GetXaxis()->SetTitleSize(0.16);
    h_ratio_pbpb_psi2s_fwd->GetXaxis()->SetLabelSize(0.16);
    h_ratio_pbpb_psi2s_fwd->GetXaxis()->SetTitleOffset(1.);
    h_ratio_pbpb_psi2s_fwd->GetXaxis()->SetTickLength(0.11);
    h_ratio_pbpb_psi2s_fwd->SetLineColor(kBlack);
    h_ratio_pbpb_psi2s_fwd->SetMarkerColor(kBlack);
    h_ratio_pbpb_psi2s_fwd->SetMarkerStyle(20);
    h_ratio_pbpb_psi2s_fwd->Draw("PE");
    jumSun(3.5,0.9,40,0.9);
    c_pT_fwd_pbpb_psi2s->SaveAs("./figs_ctauCut/compare_Eff_pT_fwd_PbPb_psi2S.pdf");

    TCanvas* c_pT_mid_pbpb_psi2s = new TCanvas("c_pT_mid_pbpb_psi2s","",550,520);
    c_pT_mid_pbpb_psi2s->cd();
    TPad *pad_F_1 = new TPad("pad_F_1","",0,0.16,0.98,1);
    pad_F_1->SetBottomMargin(0.056);
    pad_F_1->SetTicks(1,1);
    pad_F_1->Draw();
    pad_F_1->cd();
    h_eff_pbpb_psi2s_mid_1->SetLineColor(kBlue+2);
    h_eff_pbpb_psi2s_mid_1->SetMarkerColor(kBlue+2);
    h_eff_pbpb_psi2s_mid_1->SetMarkerStyle(20);
    h_eff_pbpb_psi2s_mid_2->SetLineColor(kRed+2);
    h_eff_pbpb_psi2s_mid_2->SetMarkerColor(kRed+2);
    h_eff_pbpb_psi2s_mid_2->SetMarkerStyle(21);
    h_eff_pbpb_psi2s_mid_1->SetTitle("");
    h_eff_pbpb_psi2s_mid_1->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_eff_pbpb_psi2s_mid_1->GetYaxis()->SetTitle("Efficiency");
    h_eff_pbpb_psi2s_mid_1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff_pbpb_psi2s_mid_1->GetXaxis()->SetRangeUser(6.5, 40);
    h_eff_pbpb_psi2s_mid_2->GetXaxis()->SetRangeUser(6.5, 40);
    h_eff_pbpb_psi2s_mid_1->Draw("PE");
    h_eff_pbpb_psi2s_mid_2->Draw("PE same");

    auto legend_F = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_F->AddEntry(h_eff_pbpb_psi2s_mid_1, "Without ctau cut", "lep");
    legend_F->AddEntry(h_eff_pbpb_psi2s_mid_2, "With ctau cut", "lep");
    legend_F->SetBorderSize(0);
    legend_F->SetFillColor(0);
    legend_F->Draw("E");

    drawText("|y| < 1.6", pos_x, pos_y, text_color, text_size);
    drawText("6.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("PbPb, #psi(2S)", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    TPad *pad_F_2 = new TPad("pad_F_2","",0,0.06,0.98,0.227);
    c_pT_mid_pbpb_psi2s->cd();
    pad_F_2->Draw();
    pad_F_2->cd();
    pad_F_2->SetTopMargin(0);
    pad_F_2->SetBottomMargin(0.34);
    pad_F_2->SetFillColor(0);
    pad_F_2->SetBorderMode(0);
    pad_F_2->SetBorderSize(2);
    TH1D *h_ratio_pbpb_psi2s_mid = (TH1D*)h_eff_pbpb_psi2s_mid_2->Clone("h_ratio_pbpb_psi2s_mid");
    h_ratio_pbpb_psi2s_mid->Divide(h_eff_pbpb_psi2s_mid_1);
    h_ratio_pbpb_psi2s_mid->SetTitle("");
    h_ratio_pbpb_psi2s_mid->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_ratio_pbpb_psi2s_mid->GetYaxis()->SetTitle("Ratio");
    h_ratio_pbpb_psi2s_mid->GetYaxis()->CenterTitle();
    h_ratio_pbpb_psi2s_mid->GetXaxis()->CenterTitle();
    h_ratio_pbpb_psi2s_mid->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_pbpb_psi2s_mid->GetYaxis()->SetNdivisions(505);
    h_ratio_pbpb_psi2s_mid->GetYaxis()->SetTitleSize(0.17);
    h_ratio_pbpb_psi2s_mid->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_pbpb_psi2s_mid->GetYaxis()->SetLabelSize(0.16);
    h_ratio_pbpb_psi2s_mid->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_pbpb_psi2s_mid->GetXaxis()->SetTitleSize(0.16);
    h_ratio_pbpb_psi2s_mid->GetXaxis()->SetLabelSize(0.16);
    h_ratio_pbpb_psi2s_mid->GetXaxis()->SetTitleOffset(1.);
    h_ratio_pbpb_psi2s_mid->GetXaxis()->SetTickLength(0.11);
    h_ratio_pbpb_psi2s_mid->SetLineColor(kBlack);
    h_ratio_pbpb_psi2s_mid->SetMarkerColor(kBlack);
    h_ratio_pbpb_psi2s_mid->SetMarkerStyle(20);
    h_ratio_pbpb_psi2s_mid->Draw("PE");
    jumSun(6.5,0.9,40,0.9);
    c_pT_mid_pbpb_psi2s->SaveAs("./figs_ctauCut/compare_Eff_pT_mid_PbPb_psi2S.pdf");

    TCanvas* c_pT_fwd_pp_psi2s = new TCanvas("c_pT_fwd_pp_psi2s","",550,520);
    c_pT_fwd_pp_psi2s->cd();
    TPad *pad_G_1 = new TPad("pad_G_1","",0,0.16,0.98,1);
    pad_G_1->SetBottomMargin(0.056);
    pad_G_1->SetTicks(1,1);
    pad_G_1->Draw();
    pad_G_1->cd();
    h_eff_pp_psi2s_fwd_1->SetLineColor(kBlue+2);
    h_eff_pp_psi2s_fwd_1->SetMarkerColor(kBlue+2);
    h_eff_pp_psi2s_fwd_1->SetMarkerStyle(20);
    h_eff_pp_psi2s_fwd_2->SetLineColor(kRed+2);
    h_eff_pp_psi2s_fwd_2->SetMarkerColor(kRed+2);
    h_eff_pp_psi2s_fwd_2->SetMarkerStyle(21);
    h_eff_pp_psi2s_fwd_1->SetTitle("");
    h_eff_pp_psi2s_fwd_1->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_eff_pp_psi2s_fwd_1->GetYaxis()->SetTitle("Efficiency");
    h_eff_pp_psi2s_fwd_1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff_pp_psi2s_fwd_1->GetXaxis()->SetRangeUser(3.5, 40);
    h_eff_pp_psi2s_fwd_2->GetXaxis()->SetRangeUser(3.5, 40);
    h_eff_pp_psi2s_fwd_1->Draw("PE");
    h_eff_pp_psi2s_fwd_2->Draw("PE same");

    auto legend_G = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_G->AddEntry(h_eff_pp_psi2s_fwd_1, "Without ctau cut", "lep");
    legend_G->AddEntry(h_eff_pp_psi2s_fwd_2, "With ctau cut", "lep");
    legend_G->SetBorderSize(0);
    legend_G->SetFillColor(0);
    legend_G->Draw("E");

    drawText("1.6 < |y| < 2.4", pos_x, pos_y, text_color, text_size);
    drawText("3.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("pp, #psi(2S)", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    TPad *pad_G_2 = new TPad("pad_G_2","",0,0.06,0.98,0.227);
    c_pT_fwd_pp_psi2s->cd();
    pad_G_2->Draw();
    pad_G_2->cd();
    pad_G_2->SetTopMargin(0);
    pad_G_2->SetBottomMargin(0.34);
    pad_G_2->SetFillColor(0);
    pad_G_2->SetBorderMode(0);
    pad_G_2->SetBorderSize(2);
    TH1D *h_ratio_pp_psi2s_fwd = (TH1D*)h_eff_pp_psi2s_fwd_2->Clone("h_ratio_pp_psi2s_fwd");
    h_ratio_pp_psi2s_fwd->Divide(h_eff_pp_psi2s_fwd_1);
    h_ratio_pp_psi2s_fwd->SetTitle("");
    h_ratio_pp_psi2s_fwd->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_ratio_pp_psi2s_fwd->GetYaxis()->SetTitle("Ratio");
    h_ratio_pp_psi2s_fwd->GetYaxis()->CenterTitle();
    h_ratio_pp_psi2s_fwd->GetXaxis()->CenterTitle();
    h_ratio_pp_psi2s_fwd->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_pp_psi2s_fwd->GetYaxis()->SetNdivisions(505);
    h_ratio_pp_psi2s_fwd->GetYaxis()->SetTitleSize(0.17);
    h_ratio_pp_psi2s_fwd->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_pp_psi2s_fwd->GetYaxis()->SetLabelSize(0.16);
    h_ratio_pp_psi2s_fwd->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_pp_psi2s_fwd->GetXaxis()->SetTitleSize(0.16);
    h_ratio_pp_psi2s_fwd->GetXaxis()->SetLabelSize(0.16);
    h_ratio_pp_psi2s_fwd->GetXaxis()->SetTitleOffset(1.);
    h_ratio_pp_psi2s_fwd->GetXaxis()->SetTickLength(0.11);
    h_ratio_pp_psi2s_fwd->SetLineColor(kBlack);
    h_ratio_pp_psi2s_fwd->SetMarkerColor(kBlack);
    h_ratio_pp_psi2s_fwd->SetMarkerStyle(20);
    h_ratio_pp_psi2s_fwd->Draw("PE");
    jumSun(3.5,0.9,40,0.9);
    c_pT_fwd_pp_psi2s->SaveAs("./figs_ctauCut/compare_Eff_pT_fwd_pp_psi2S.pdf");

    TCanvas* c_pT_mid_pp_psi2s = new TCanvas("c_pT_mid_pp_psi2s","",550,520);
    c_pT_mid_pp_psi2s->cd();
    TPad *pad_H_1 = new TPad("pad_H_1","",0,0.16,0.98,1);
    pad_H_1->SetBottomMargin(0.056);
    pad_H_1->SetTicks(1,1);
    pad_H_1->Draw();
    pad_H_1->cd();
    h_eff_pp_psi2s_mid_1->SetLineColor(kBlue+2);
    h_eff_pp_psi2s_mid_1->SetMarkerColor(kBlue+2);
    h_eff_pp_psi2s_mid_1->SetMarkerStyle(20);
    h_eff_pp_psi2s_mid_2->SetLineColor(kRed+2);
    h_eff_pp_psi2s_mid_2->SetMarkerColor(kRed+2);
    h_eff_pp_psi2s_mid_2->SetMarkerStyle(21);
    h_eff_pp_psi2s_mid_1->SetTitle("");
    h_eff_pp_psi2s_mid_1->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_eff_pp_psi2s_mid_1->GetYaxis()->SetTitle("Efficiency");
    h_eff_pp_psi2s_mid_1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff_pp_psi2s_mid_1->GetXaxis()->SetRangeUser(6.5, 40);
    h_eff_pp_psi2s_mid_2->GetXaxis()->SetRangeUser(6.5, 40);
    h_eff_pp_psi2s_mid_1->Draw("PE");
    h_eff_pp_psi2s_mid_2->Draw("PE same");

    auto legend_H = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_H->AddEntry(h_eff_pp_psi2s_mid_1, "Without ctau cut", "lep");
    legend_H->AddEntry(h_eff_pp_psi2s_mid_2, "With ctau cut", "lep");
    legend_H->SetBorderSize(0);
    legend_H->SetFillColor(0);
    legend_H->Draw("E");

    drawText("|y| < 1.6", pos_x, pos_y, text_color, text_size);
    drawText("6.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("pp, #psi(2S)", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    TPad *pad_H_2 = new TPad("pad_H_2","",0,0.06,0.98,0.227);
    c_pT_mid_pp_psi2s->cd();
    pad_H_2->Draw();
    pad_H_2->cd();
    pad_H_2->SetTopMargin(0);
    pad_H_2->SetBottomMargin(0.34);
    pad_H_2->SetFillColor(0);
    pad_H_2->SetBorderMode(0);
    pad_H_2->SetBorderSize(2);
    TH1D *h_ratio_pp_psi2s_mid = (TH1D*)h_eff_pp_psi2s_mid_2->Clone("h_ratio_pp_psi2s_mid");
    h_ratio_pp_psi2s_mid->Divide(h_eff_pp_psi2s_mid_1);
    h_ratio_pp_psi2s_mid->SetTitle("");
    h_ratio_pp_psi2s_mid->GetXaxis()->SetTitle("p_{T} (GeV/c)");
    h_ratio_pp_psi2s_mid->GetYaxis()->SetTitle("Ratio");
    h_ratio_pp_psi2s_mid->GetYaxis()->CenterTitle();
    h_ratio_pp_psi2s_mid->GetXaxis()->CenterTitle();
    h_ratio_pp_psi2s_mid->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_pp_psi2s_mid->GetYaxis()->SetNdivisions(505);
    h_ratio_pp_psi2s_mid->GetYaxis()->SetTitleSize(0.17);
    h_ratio_pp_psi2s_mid->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_pp_psi2s_mid->GetYaxis()->SetLabelSize(0.16);
    h_ratio_pp_psi2s_mid->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_pp_psi2s_mid->GetXaxis()->SetTitleSize(0.16);
    h_ratio_pp_psi2s_mid->GetXaxis()->SetLabelSize(0.16);
    h_ratio_pp_psi2s_mid->GetXaxis()->SetTitleOffset(1.);
    h_ratio_pp_psi2s_mid->GetXaxis()->SetTickLength(0.11);
    h_ratio_pp_psi2s_mid->SetLineColor(kBlack);
    h_ratio_pp_psi2s_mid->SetMarkerColor(kBlack);
    h_ratio_pp_psi2s_mid->SetMarkerStyle(20);
    h_ratio_pp_psi2s_mid->Draw("PE");
    jumSun(6.5,0.9,40,0.9);
    c_pT_mid_pp_psi2s->SaveAs("./figs_ctauCut/compare_Eff_pT_mid_pp_psi2S.pdf");

    TCanvas* c_cent_fwd = new TCanvas("c_cent_fwd","",550,520);
    c_cent_fwd->cd();
    TPad *pad_I_1 = new TPad("pad_I_1","",0,0.16,0.98,1);
    pad_I_1->SetBottomMargin(0.056);
    pad_I_1->SetTicks(1,1);
    pad_I_1->Draw();
    pad_I_1->cd();
    h_eff_cent_fwd_1->SetLineColor(kBlue+2);
    h_eff_cent_fwd_1->SetMarkerColor(kBlue+2);
    h_eff_cent_fwd_1->SetMarkerStyle(20);
    h_eff_cent_fwd_2->SetLineColor(kRed+2);
    h_eff_cent_fwd_2->SetMarkerColor(kRed+2);
    h_eff_cent_fwd_2->SetMarkerStyle(21);
    h_eff_cent_fwd_1->SetTitle("");
    h_eff_cent_fwd_1->GetXaxis()->SetTitle("cBin");
    h_eff_cent_fwd_1->GetYaxis()->SetTitle("Efficiency");
    h_eff_cent_fwd_1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff_cent_fwd_1->GetXaxis()->SetRangeUser(0, 180);
    h_eff_cent_fwd_2->GetXaxis()->SetRangeUser(0, 180);
    h_eff_cent_fwd_1->Draw("PE");
    h_eff_cent_fwd_2->Draw("PE same");

    auto legend_I = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_I->AddEntry(h_eff_cent_fwd_1, "Without ctau cut", "lep");
    legend_I->AddEntry(h_eff_cent_fwd_2, "With ctau cut", "lep");
    legend_I->SetBorderSize(0);
    legend_I->SetFillColor(0);
    legend_I->Draw("E");

    drawText("1.6 < |y| < 2.4", pos_x, pos_y, text_color, text_size);
    drawText("3.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("PbPb, J/#psi", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    TPad *pad_I_2 = new TPad("pad_I_2","",0,0.06,0.98,0.227);
    c_cent_fwd->cd();
    pad_I_2->Draw();
    pad_I_2->cd();
    pad_I_2->SetTopMargin(0);
    pad_I_2->SetBottomMargin(0.34);
    pad_I_2->SetFillColor(0);
    pad_I_2->SetBorderMode(0);
    pad_I_2->SetBorderSize(2);
    TH1D *h_ratio_cent_fwd = (TH1D*)h_eff_cent_fwd_2->Clone("h_ratio_cent_fwd");
    h_ratio_cent_fwd->Divide(h_eff_cent_fwd_1);
    h_ratio_cent_fwd->SetTitle("");
    h_ratio_cent_fwd->GetXaxis()->SetTitle("cBin");
    h_ratio_cent_fwd->GetYaxis()->SetTitle("Ratio");
    h_ratio_cent_fwd->GetYaxis()->CenterTitle();
    h_ratio_cent_fwd->GetXaxis()->CenterTitle();
    h_ratio_cent_fwd->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_cent_fwd->GetYaxis()->SetNdivisions(505);
    h_ratio_cent_fwd->GetYaxis()->SetTitleSize(0.17);
    h_ratio_cent_fwd->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_cent_fwd->GetYaxis()->SetLabelSize(0.16);
    h_ratio_cent_fwd->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_cent_fwd->GetXaxis()->SetTitleSize(0.16);
    h_ratio_cent_fwd->GetXaxis()->SetLabelSize(0.16);
    h_ratio_cent_fwd->GetXaxis()->SetTitleOffset(1.);
    h_ratio_cent_fwd->GetXaxis()->SetTickLength(0.11);
    h_ratio_cent_fwd->SetLineColor(kBlack);
    h_ratio_cent_fwd->SetMarkerColor(kBlack);
    h_ratio_cent_fwd->SetMarkerStyle(20);
    h_ratio_cent_fwd->Draw("PE");
    jumSun(0,0.9,180,0.9);
    c_cent_fwd->SaveAs("./figs_ctauCut/compare_Eff_cent_fwd_PbPb_Jpsi.pdf");

    TCanvas* c_cent_mid = new TCanvas("c_cent_mid","",550,520);
    c_cent_mid->cd();
    TPad *pad_J_1 = new TPad("pad_J_1","",0,0.16,0.98,1);
    pad_J_1->SetBottomMargin(0.056);
    pad_J_1->SetTicks(1,1);
    pad_J_1->Draw();
    pad_J_1->cd();
    h_eff_cent_mid_1->SetLineColor(kBlue+2);
    h_eff_cent_mid_1->SetMarkerColor(kBlue+2);
    h_eff_cent_mid_1->SetMarkerStyle(20);
    h_eff_cent_mid_2->SetLineColor(kRed+2);
    h_eff_cent_mid_2->SetMarkerColor(kRed+2);
    h_eff_cent_mid_2->SetMarkerStyle(21);
    h_eff_cent_mid_1->SetTitle("");
    h_eff_cent_mid_1->GetXaxis()->SetTitle("cBin");
    h_eff_cent_mid_1->GetYaxis()->SetTitle("Efficiency");
    h_eff_cent_mid_1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff_cent_mid_1->GetXaxis()->SetRangeUser(0, 180);
    h_eff_cent_mid_2->GetXaxis()->SetRangeUser(0, 180);
    h_eff_cent_mid_1->Draw("PE");
    h_eff_cent_mid_2->Draw("PE same");

    auto legend_J = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_J->AddEntry(h_eff_cent_mid_1, "Without ctau cut", "lep");
    legend_J->AddEntry(h_eff_cent_mid_2, "With ctau cut", "lep");
    legend_J->SetBorderSize(0);
    legend_J->SetFillColor(0);
    legend_J->Draw("E");

    drawText("|y| < 1.6", pos_x, pos_y, text_color, text_size);
    drawText("6.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("PbPb, J/#psi", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    TPad *pad_J_2 = new TPad("pad_J_2","",0,0.06,0.98,0.227);
    c_cent_mid->cd();
    pad_J_2->Draw();
    pad_J_2->cd();
    pad_J_2->SetTopMargin(0);
    pad_J_2->SetBottomMargin(0.34);
    pad_J_2->SetFillColor(0);
    pad_J_2->SetBorderMode(0);
    pad_J_2->SetBorderSize(2);
    TH1D *h_ratio_cent_mid = (TH1D*)h_eff_cent_mid_2->Clone("h_ratio_cent_mid");
    h_ratio_cent_mid->Divide(h_eff_cent_mid_1);
    h_ratio_cent_mid->SetTitle("");
    h_ratio_cent_mid->GetXaxis()->SetTitle("cBin");
    h_ratio_cent_mid->GetYaxis()->SetTitle("Ratio");
    h_ratio_cent_mid->GetYaxis()->CenterTitle();
    h_ratio_cent_mid->GetXaxis()->CenterTitle();
    h_ratio_cent_mid->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_cent_mid->GetYaxis()->SetNdivisions(505);
    h_ratio_cent_mid->GetYaxis()->SetTitleSize(0.17);
    h_ratio_cent_mid->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_cent_mid->GetYaxis()->SetLabelSize(0.16);
    h_ratio_cent_mid->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_cent_mid->GetXaxis()->SetTitleSize(0.16);
    h_ratio_cent_mid->GetXaxis()->SetLabelSize(0.16);
    h_ratio_cent_mid->GetXaxis()->SetTitleOffset(1.);
    h_ratio_cent_mid->GetXaxis()->SetTickLength(0.11);
    h_ratio_cent_mid->SetLineColor(kBlack);
    h_ratio_cent_mid->SetMarkerColor(kBlack);
    h_ratio_cent_mid->SetMarkerStyle(20);
    h_ratio_cent_mid->Draw("PE");
    jumSun(0,0.9,180,0.9);
    c_cent_mid->SaveAs("./figs_ctauCut/compare_Eff_cent_mid_PbPb_Jpsi.pdf");

    TCanvas* c_cent_fwd_pbpb_psi2s = new TCanvas("c_cent_fwd_pbpb_psi2s","",550,520);
    c_cent_fwd_pbpb_psi2s->cd();
    TPad *pad_K_1 = new TPad("pad_K_1","",0,0.16,0.98,1);
    pad_K_1->SetBottomMargin(0.056);
    pad_K_1->SetTicks(1,1);
    pad_K_1->Draw();
    pad_K_1->cd();
    h_eff_cent_pbpb_psi2s_fwd_1->SetLineColor(kBlue+2);
    h_eff_cent_pbpb_psi2s_fwd_1->SetMarkerColor(kBlue+2);
    h_eff_cent_pbpb_psi2s_fwd_1->SetMarkerStyle(20);
    h_eff_cent_pbpb_psi2s_fwd_2->SetLineColor(kRed+2);
    h_eff_cent_pbpb_psi2s_fwd_2->SetMarkerColor(kRed+2);
    h_eff_cent_pbpb_psi2s_fwd_2->SetMarkerStyle(21);
    h_eff_cent_pbpb_psi2s_fwd_1->SetTitle("");
    h_eff_cent_pbpb_psi2s_fwd_1->GetXaxis()->SetTitle("cBin");
    h_eff_cent_pbpb_psi2s_fwd_1->GetYaxis()->SetTitle("Efficiency");
    h_eff_cent_pbpb_psi2s_fwd_1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff_cent_pbpb_psi2s_fwd_1->GetXaxis()->SetRangeUser(0, 180);
    h_eff_cent_pbpb_psi2s_fwd_2->GetXaxis()->SetRangeUser(0, 180);
    h_eff_cent_pbpb_psi2s_fwd_1->Draw("PE");
    h_eff_cent_pbpb_psi2s_fwd_2->Draw("PE same");

    auto legend_K = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_K->AddEntry(h_eff_cent_pbpb_psi2s_fwd_1, "Without ctau cut", "lep");
    legend_K->AddEntry(h_eff_cent_pbpb_psi2s_fwd_2, "With ctau cut", "lep");
    legend_K->SetBorderSize(0);
    legend_K->SetFillColor(0);
    legend_K->Draw("E");

    drawText("1.6 < |y| < 2.4", pos_x, pos_y, text_color, text_size);
    drawText("3 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("PbPb, #psi(2S)", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    TPad *pad_K_2 = new TPad("pad_K_2","",0,0.06,0.98,0.227);
    c_cent_fwd_pbpb_psi2s->cd();
    pad_K_2->Draw();
    pad_K_2->cd();
    pad_K_2->SetTopMargin(0);
    pad_K_2->SetBottomMargin(0.34);
    pad_K_2->SetFillColor(0);
    pad_K_2->SetBorderMode(0);
    pad_K_2->SetBorderSize(2);
    TH1D *h_ratio_cent_pbpb_psi2s_fwd = (TH1D*)h_eff_cent_pbpb_psi2s_fwd_2->Clone("h_ratio_cent_pbpb_psi2s_fwd");
    h_ratio_cent_pbpb_psi2s_fwd->Divide(h_eff_cent_pbpb_psi2s_fwd_1);
    h_ratio_cent_pbpb_psi2s_fwd->SetTitle("");
    h_ratio_cent_pbpb_psi2s_fwd->GetXaxis()->SetTitle("cBin");
    h_ratio_cent_pbpb_psi2s_fwd->GetYaxis()->SetTitle("Ratio");
    h_ratio_cent_pbpb_psi2s_fwd->GetYaxis()->CenterTitle();
    h_ratio_cent_pbpb_psi2s_fwd->GetXaxis()->CenterTitle();
    h_ratio_cent_pbpb_psi2s_fwd->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_cent_pbpb_psi2s_fwd->GetYaxis()->SetNdivisions(505);
    h_ratio_cent_pbpb_psi2s_fwd->GetYaxis()->SetTitleSize(0.17);
    h_ratio_cent_pbpb_psi2s_fwd->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_cent_pbpb_psi2s_fwd->GetYaxis()->SetLabelSize(0.16);
    h_ratio_cent_pbpb_psi2s_fwd->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_cent_pbpb_psi2s_fwd->GetXaxis()->SetTitleSize(0.16);
    h_ratio_cent_pbpb_psi2s_fwd->GetXaxis()->SetLabelSize(0.16);
    h_ratio_cent_pbpb_psi2s_fwd->GetXaxis()->SetTitleOffset(1.);
    h_ratio_cent_pbpb_psi2s_fwd->GetXaxis()->SetTickLength(0.11);
    h_ratio_cent_pbpb_psi2s_fwd->SetLineColor(kBlack);
    h_ratio_cent_pbpb_psi2s_fwd->SetMarkerColor(kBlack);
    h_ratio_cent_pbpb_psi2s_fwd->SetMarkerStyle(20);
    h_ratio_cent_pbpb_psi2s_fwd->Draw("PE");
    jumSun(0,0.9,180,0.9);
    c_cent_fwd_pbpb_psi2s->SaveAs("./figs_ctauCut/compare_Eff_cent_fwd_PbPb_psi2S.pdf");

    TCanvas* c_cent_mid_pbpb_psi2s = new TCanvas("c_cent_mid_pbpb_psi2s","",550,520);
    c_cent_mid_pbpb_psi2s->cd();
    TPad *pad_L_1 = new TPad("pad_L_1","",0,0.16,0.98,1);
    pad_L_1->SetBottomMargin(0.056);
    pad_L_1->SetTicks(1,1);
    pad_L_1->Draw();
    pad_L_1->cd();
    h_eff_cent_pbpb_psi2s_mid_1->SetLineColor(kBlue+2);
    h_eff_cent_pbpb_psi2s_mid_1->SetMarkerColor(kBlue+2);
    h_eff_cent_pbpb_psi2s_mid_1->SetMarkerStyle(20);
    h_eff_cent_pbpb_psi2s_mid_2->SetLineColor(kRed+2);
    h_eff_cent_pbpb_psi2s_mid_2->SetMarkerColor(kRed+2);
    h_eff_cent_pbpb_psi2s_mid_2->SetMarkerStyle(21);
    h_eff_cent_pbpb_psi2s_mid_1->SetTitle("");
    h_eff_cent_pbpb_psi2s_mid_1->GetXaxis()->SetTitle("cBin");
    h_eff_cent_pbpb_psi2s_mid_1->GetYaxis()->SetTitle("Efficiency");
    h_eff_cent_pbpb_psi2s_mid_1->GetYaxis()->SetRangeUser(0, 1.2);
    h_eff_cent_pbpb_psi2s_mid_1->GetXaxis()->SetRangeUser(0, 180);
    h_eff_cent_pbpb_psi2s_mid_2->GetXaxis()->SetRangeUser(0, 180);
    h_eff_cent_pbpb_psi2s_mid_1->Draw("PE");
    h_eff_cent_pbpb_psi2s_mid_2->Draw("PE same");

    auto legend_L = new TLegend(0.55, 0.68, 0.88, 0.84);
    legend_L->AddEntry(h_eff_cent_pbpb_psi2s_mid_1, "Without ctau cut", "lep");
    legend_L->AddEntry(h_eff_cent_pbpb_psi2s_mid_2, "With ctau cut", "lep");
    legend_L->SetBorderSize(0);
    legend_L->SetFillColor(0);
    legend_L->Draw("E");

    drawText("|y| < 1.6", pos_x, pos_y, text_color, text_size);
    drawText("6.5 < p_{T} < 40 GeV/c", pos_x, pos_y - pos_y_diff, text_color, text_size);
    drawText("PbPb, #psi(2S)", pos_x, pos_y - pos_y_diff*2, text_color, text_size);

    TPad *pad_L_2 = new TPad("pad_L_2","",0,0.06,0.98,0.227);
    c_cent_mid_pbpb_psi2s->cd();
    pad_L_2->Draw();
    pad_L_2->cd();
    pad_L_2->SetTopMargin(0);
    pad_L_2->SetBottomMargin(0.34);
    pad_L_2->SetFillColor(0);
    pad_L_2->SetBorderMode(0);
    pad_L_2->SetBorderSize(2);
    TH1D *h_ratio_cent_pbpb_psi2s_mid = (TH1D*)h_eff_cent_pbpb_psi2s_mid_2->Clone("h_ratio_cent_pbpb_psi2s_mid");
    h_ratio_cent_pbpb_psi2s_mid->Divide(h_eff_cent_pbpb_psi2s_mid_1);
    h_ratio_cent_pbpb_psi2s_mid->SetTitle("");
    h_ratio_cent_pbpb_psi2s_mid->GetXaxis()->SetTitle("cBin");
    h_ratio_cent_pbpb_psi2s_mid->GetYaxis()->SetTitle("Ratio");
    h_ratio_cent_pbpb_psi2s_mid->GetYaxis()->CenterTitle();
    h_ratio_cent_pbpb_psi2s_mid->GetXaxis()->CenterTitle();
    h_ratio_cent_pbpb_psi2s_mid->GetYaxis()->SetRangeUser(0.83, 0.97);
    h_ratio_cent_pbpb_psi2s_mid->GetYaxis()->SetNdivisions(505);
    h_ratio_cent_pbpb_psi2s_mid->GetYaxis()->SetTitleSize(0.17);
    h_ratio_cent_pbpb_psi2s_mid->GetYaxis()->SetTitleOffset(0.28);
    h_ratio_cent_pbpb_psi2s_mid->GetYaxis()->SetLabelSize(0.16);
    h_ratio_cent_pbpb_psi2s_mid->GetYaxis()->SetLabelOffset(0.005);
    h_ratio_cent_pbpb_psi2s_mid->GetXaxis()->SetTitleSize(0.16);
    h_ratio_cent_pbpb_psi2s_mid->GetXaxis()->SetLabelSize(0.16);
    h_ratio_cent_pbpb_psi2s_mid->GetXaxis()->SetTitleOffset(1.);
    h_ratio_cent_pbpb_psi2s_mid->GetXaxis()->SetTickLength(0.11);
    h_ratio_cent_pbpb_psi2s_mid->SetLineColor(kBlack);
    h_ratio_cent_pbpb_psi2s_mid->SetMarkerColor(kBlack);
    h_ratio_cent_pbpb_psi2s_mid->SetMarkerStyle(20);
    h_ratio_cent_pbpb_psi2s_mid->Draw("PE");
    jumSun(0,0.9,180,0.9);
    c_cent_mid_pbpb_psi2s->SaveAs("./figs_ctauCut/compare_Eff_cent_mid_PbPb_psi2S.pdf");

}